# Generated by Django 5.0.2 on 2024-02-15 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_os', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistinstalacao',
            options={'verbose_name_plural': 'Checklists de Instalações'},
        ),
        migrations.AlterModelOptions(
            name='itemchecklist',
            options={'verbose_name_plural': 'Itens Checklist'},
        ),
        migrations.AlterModelOptions(
            name='ordemdeservico',
            options={'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.RemoveField(
            model_name='checklistinstalacao',
            name='item',
        ),
        migrations.AddField(
            model_name='checklistinstalacao',
            name='nome',
            field=models.CharField(default='CheckList-eld>', max_length=255),
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='checklist_instalacao',
            field=models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, to='field_os.checklistinstalacao'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='tipo',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('boolean', 'Boolean')], default='texto', max_length=50),
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='valor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checklistinstalacao',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemchecklist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
