# Generated by Django 5.0.2 on 2024-02-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_os', '0002_alter_checklistinstalacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='id_os',
            field=models.CharField(default='OS-YYMM-XXXX', editable=False, max_length=20, unique=True),
        ),
    ]
